[features]
seeds = false
[programs.localnet]
locker_manager = "7LGfdonJVsPaB3LzfVvDGE9jwHseFVDkg8ZrJfwhiAzw"
pool_manager = "362QKmGMs4ZGiSfuQCXCEAcW6gFExy9XmZM2Cki89rWw"
pool_reward_keeper = "9dfVBXMVk4GmmkVvZuY3z5cqAcWn96N7fwBVuVbhpfJd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
